#!/usr/bin/env ruby

require 'fileutils'
require 'json_roa/client'
require 'json_roa/client'
require 'mime/types'
require 'open-uri'
require 'pry'
require 'thread/future'
require 'thread/pool'


root_relation= JSON_ROA::Client.connect \
  "https://ci2.zhdk.ch/cider-ci/api/v2/" do |conn|
  conn.basic_auth(ENV['CIDER_CI_USERNAME'],ENV['CIDER_CI_PASSWORD'])
  conn.ssl.verify= false
end


# Suggested exercise 
#
# Pick any execution; compute the failed/success statistics for tasks and trails
# and attach the result in json format to the tree_id
#
# some inspiration: 
#
# https://github.com/cider-ci/cider-ci_ruby-support/blob/master/bin/cider-ci_coverage
#

binding.pry
